const countries = [
  { id: 1, country_name: 'United States', country_code: 'US', currency_code: 'USD' },
  { id: 2, country_name: 'Canada', country_code: 'CA', currency_code: 'CAD' },
  { id: 3, country_name: 'United Kingdom', country_code: 'GB', currency_code: 'GBP' },
  { id: 4, country_name: 'Australia', country_code: 'AU', currency_code: 'AUD' },
  { id: 5, country_name: 'New Zealand', country_code: 'NZ', currency_code: 'NZD' },
  { id: 6, country_name: 'Ireland', country_code: 'IE', currency_code: 'EUR' },
  { id: 7, country_name: 'France', country_code: 'FR', currency_code: 'EUR' },
  { id: 8, country_name: 'Germany', country_code: 'DE', currency_code: 'EUR' },
  { id: 9, country_name: 'Spain', country_code: 'ES', currency_code: 'EUR' },
  { id: 10, country_name: 'Italy', country_code: 'IT', currency_code: 'EUR' },
  { id: 11, country_name: 'Netherlands', country_code: 'NL', currency_code: 'EUR' },
  { id: 12, country_name: 'Belgium', country_code: 'BE', currency_code: 'EUR' },
  { id: 13, country_name: 'Portugal', country_code: 'PT', currency_code: 'EUR' },
  { id: 14, country_name: 'Switzerland', country_code: 'CH', currency_code: 'CHF' },
  { id: 15, country_name: 'Norway', country_code: 'NO', currency_code: 'NOK' },
  { id: 16, country_name: 'Sweden', country_code: 'SE', currency_code: 'SEK' },
  { id: 17, country_name: 'Denmark', country_code: 'DK', currency_code: 'DKK' },
  { id: 18, country_name: 'Poland', country_code: 'PL', currency_code: 'PLN' },
  { id: 19, country_name: 'Czechia', country_code: 'CZ', currency_code: 'CZK' },
  { id: 20, country_name: 'Hungary', country_code: 'HU', currency_code: 'HUF' },
  { id: 21, country_name: 'Romania', country_code: 'RO', currency_code: 'RON' },
  { id: 22, country_name: 'Bulgaria', country_code: 'BG', currency_code: 'BGN' },
  { id: 23, country_name: 'Greece', country_code: 'GR', currency_code: 'EUR' },
  { id: 24, country_name: 'Turkey', country_code: 'TR', currency_code: 'TRY' },
  { id: 25, country_name: 'Russia', country_code: 'RU', currency_code: 'RUB' },
  { id: 26, country_name: 'Ukraine', country_code: 'UA', currency_code: 'UAH' },
  { id: 27, country_name: 'Israel', country_code: 'IL', currency_code: 'ILS' },
  { id: 28, country_name: 'Saudi Arabia', country_code: 'SA', currency_code: 'SAR' },
  { id: 29, country_name: 'United Arab Emirates', country_code: 'AE', currency_code: 'AED' },
  { id: 30, country_name: 'Qatar', country_code: 'QA', currency_code: 'QAR' },
  { id: 31, country_name: 'Kuwait', country_code: 'KW', currency_code: 'KWD' },
  { id: 32, country_name: 'South Africa', country_code: 'ZA', currency_code: 'ZAR' },
  { id: 33, country_name: 'Nigeria', country_code: 'NG', currency_code: 'NGN' },
  { id: 34, country_name: 'Kenya', country_code: 'KE', currency_code: 'KES' },
  { id: 35, country_name: 'Ghana', country_code: 'GH', currency_code: 'GHS' },
  { id: 36, country_name: 'Egypt', country_code: 'EG', currency_code: 'EGP' },
  { id: 37, country_name: 'Morocco', country_code: 'MA', currency_code: 'MAD' },
  { id: 38, country_name: 'Algeria', country_code: 'DZ', currency_code: 'DZD' },
  { id: 39, country_name: 'Tunisia', country_code: 'TN', currency_code: 'TND' },
  { id: 40, country_name: 'Ethiopia', country_code: 'ET', currency_code: 'ETB' },
  { id: 41, country_name: 'India', country_code: 'IN', currency_code: 'INR' },
  { id: 42, country_name: 'Pakistan', country_code: 'PK', currency_code: 'PKR' },
  { id: 43, country_name: 'Bangladesh', country_code: 'BD', currency_code: 'BDT' },
  { id: 44, country_name: 'Sri Lanka', country_code: 'LK', currency_code: 'LKR' },
  { id: 45, country_name: 'Nepal', country_code: 'NP', currency_code: 'NPR' },
  { id: 46, country_name: 'China', country_code: 'CN', currency_code: 'CNY' },
  { id: 47, country_name: 'Japan', country_code: 'JP', currency_code: 'JPY' },
  { id: 48, country_name: 'South Korea', country_code: 'KR', currency_code: 'KRW' },
  { id: 49, country_name: 'Singapore', country_code: 'SG', currency_code: 'SGD' },
  { id: 50, country_name: 'Malaysia', country_code: 'MY', currency_code: 'MYR' },
  { id: 51, country_name: 'Thailand', country_code: 'TH', currency_code: 'THB' },
  { id: 52, country_name: 'Vietnam', country_code: 'VN', currency_code: 'VND' },
  { id: 53, country_name: 'Philippines', country_code: 'PH', currency_code: 'PHP' },
  { id: 54, country_name: 'Indonesia', country_code: 'ID', currency_code: 'IDR' },
  { id: 55, country_name: 'Hong Kong', country_code: 'HK', currency_code: 'HKD' },
  { id: 56, country_name: 'Taiwan', country_code: 'TW', currency_code: 'TWD' },
  { id: 57, country_name: 'Brazil', country_code: 'BR', currency_code: 'BRL' },
  { id: 58, country_name: 'Mexico', country_code: 'MX', currency_code: 'MXN' },
  { id: 59, country_name: 'Argentina', country_code: 'AR', currency_code: 'ARS' },
  { id: 60, country_name: 'Chile', country_code: 'CL', currency_code: 'CLP' },
  { id: 61, country_name: 'Colombia', country_code: 'CO', currency_code: 'COP' },
  { id: 62, country_name: 'Peru', country_code: 'PE', currency_code: 'PEN' },
  { id: 63, country_name: 'Venezuela', country_code: 'VE', currency_code: 'VES' }
];

export default countries;
